# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dalli/all/dalli.rbi
#
# dalli-3.2.8

module Dalli
end
class Dalli::Compressor
end
class Dalli::GzipCompressor
end
class Dalli::Client
end
class Dalli::KeyManager
end
class Dalli::PipelinedGetter
end
class Dalli::Ring
end
class Dalli::Ring::Entry
end
module Dalli::Protocol
end
class Dalli::Protocol::Base
  extend Forwardable
end
class Dalli::Protocol::Binary < Dalli::Protocol::Base
  include Dalli::Protocol::Binary::SaslAuthentication
end
class Dalli::Protocol::Binary::RequestFormatter
end
class Dalli::Protocol::Binary::ResponseHeader
end
class Dalli::Protocol::Binary::ResponseProcessor
end
module Dalli::Protocol::Binary::SaslAuthentication
end
module Dalli::PIDCache
end
module Dalli::PIDCache::CoreExt
end
class Dalli::Protocol::ConnectionManager
end
class Dalli::Protocol::Meta < Dalli::Protocol::Base
end
class Dalli::Protocol::Meta::KeyRegularizer
end
class Dalli::Protocol::Meta::RequestFormatter
end
class Dalli::Protocol::Meta::ResponseProcessor
end
class Dalli::Protocol::ResponseBuffer
end
class Dalli::Protocol::ServerConfigParser
end
class Dalli::Protocol::TtlSanitizer
end
class Dalli::Protocol::ValueCompressor
end
class Dalli::Protocol::ValueMarshaller
  extend Forwardable
end
class Dalli::Protocol::ValueSerializer
end
module Dalli::ServersArgNormalizer
end
module Dalli::Socket
end
module Dalli::Socket::InstanceMethods
end
class Dalli::Socket::SSLSocket < OpenSSL::SSL::SSLSocket
  include Dalli::Socket::InstanceMethods
end
class Dalli::Socket::TCP < TCPSocket
  include Dalli::Socket::InstanceMethods
end
class Dalli::Socket::UNIX < UNIXSocket
  include Dalli::Socket::InstanceMethods
end
module Dalli::Threadsafe
end
class Dalli::DalliError < RuntimeError
end
class Dalli::NetworkError < Dalli::DalliError
end
class Dalli::RingError < Dalli::DalliError
end
class Dalli::MarshalError < Dalli::DalliError
end
class Dalli::UnmarshalError < Dalli::DalliError
end
class Dalli::ValueOverMaxSize < Dalli::DalliError
end
class Dalli::NotPermittedMultiOpError < Dalli::DalliError
end
class Dalli::NilObject
end
