# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faker/all/faker.rbi
#
# faker-3.4.2

module Faker
  include Faker::Deprecator
  include Faker::Deprecator
  include Faker::Deprecator
end
module Faker::Base58
end
module Faker::Char
end
module Faker::Deprecator
end
class PositionalGenerator
end
class PositionalGenerator::Builder
end
class PositionalGenerator::Builder::Group
end
class PositionalGenerator::Builder::Oneof
end
class PositionalGenerator::Builder::Oneof::OneofSelector
end
class PositionalGenerator::Builder::Int
end
class PositionalGenerator::Builder::Letter
end
class PositionalGenerator::Builder::Literal
end
class PositionalGenerator::Builder::Computed
end
class Faker::UniqueGenerator
end
class Faker::UniqueGenerator::RetryLimitExceeded < StandardError
end
class Faker::Blockchain
end
class Faker::Blockchain::Aeternity < Faker::Base
end
class Faker::Blockchain::Bitcoin < Faker::Base
end
class Faker::Blockchain::Ethereum < Faker::Base
end
class Faker::Blockchain::Tezos < Faker::Base
end
class Faker::Book < Faker::Base
end
class Faker::Books
end
class Faker::Books::CultureSeries < Faker::Base
end
class Faker::Books::Dune < Faker::Base
end
class Faker::Books::Lovecraft < Faker::Base
end
class Faker::Books::TheKingkillerChronicle < Faker::Base
end
class Faker::Creature
end
class Faker::Creature::Animal < Faker::Base
end
class Faker::Creature::Bird < Faker::Base
end
class Faker::Creature::Cat < Faker::Base
end
class Faker::Creature::Dog < Faker::Base
end
class Faker::Creature::Horse < Faker::Base
end
class Faker::Address < Faker::Base
end
class Faker::Adjective < Faker::Base
end
class Faker::Alphanumeric < Faker::Base
end
class Faker::Ancient < Faker::Base
end
class Faker::App < Faker::Base
end
class Faker::Appliance < Faker::Base
end
class Faker::Artist < Faker::Base
end
class Faker::Avatar < Faker::Base
end
class Faker::Bank < Faker::Base
end
class Faker::Barcode < Faker::Base
end
class Faker::Beer < Faker::Base
end
class Faker::Blood < Faker::Base
end
class Faker::Boolean < Faker::Base
end
class Faker::BossaNova < Faker::Base
end
class Faker::Business < Faker::Base
end
class Faker::Camera < Faker::Base
end
class Faker::Cannabis < Faker::Base
end
class Faker::ChileRut < Faker::Base
end
class Faker::ChuckNorris < Faker::Base
end
class Faker::Code < Faker::Base
end
class Faker::Coffee < Faker::Base
end
class Faker::Coin < Faker::Base
end
class Faker::Color < Faker::Base
end
class Faker::Commerce < Faker::Base
end
class Faker::Company < Faker::Base
end
class Faker::Compass < Faker::Base
end
class Faker::Computer < Faker::Base
end
class Faker::Construction < Faker::Base
end
class Faker::Cosmere < Faker::Base
end
class Faker::Crypto < Faker::Base
end
class Faker::CryptoCoin < Faker::Base
end
class Faker::Currency < Faker::Base
end
class Faker::Date < Faker::Base
end
class Faker::DcComics < Faker::Base
end
class Faker::Demographic < Faker::Base
end
class Faker::Dessert < Faker::Base
end
class Faker::Device < Faker::Base
end
class Faker::DrivingLicence < Faker::Base
end
class Faker::InvalidStatePassed < StandardError
end
class Faker::Drone < Faker::Base
end
class Faker::Educator < Faker::Base
end
class Faker::ElectricalComponents < Faker::Base
end
class Faker::Emotion < Faker::Base
end
class Faker::Esport < Faker::Base
end
class Faker::File < Faker::Base
end
class Faker::Finance < Faker::Base
end
class Faker::Food < Faker::Base
end
class Faker::FunnyName < Faker::Base
end
class Faker::Gender < Faker::Base
end
class Faker::GreekPhilosophers < Faker::Base
end
class Faker::Hacker < Faker::Base
end
class Faker::Hipster < Faker::Base
end
class Faker::Hobby < Faker::Base
end
class Faker::House < Faker::Base
end
class Faker::HTML < Faker::Base
end
class Faker::IdNumber < Faker::Base
end
class Faker::IndustrySegments < Faker::Base
end
class Faker::Internet < Faker::Base
end
class Faker::Internet::HTTP < Faker::Base
end
class Faker::Invoice < Faker::Base
end
class Faker::Job < Faker::Base
end
class Faker::Json < Faker::Base
end
class Faker::Kpop < Faker::Base
end
class Faker::Lorem < Faker::Base
end
class Faker::LoremFlickr < Faker::Base
end
class Faker::Markdown < Faker::Base
end
class Faker::Marketing < Faker::Base
end
class Faker::Measurement < Faker::Base
end
class Faker::Military < Faker::Base
end
class Faker::Mountain < Faker::Base
end
class Faker::Name < Faker::Base
end
class Faker::Nation < Faker::Base
end
class Faker::NationalHealthService < Faker::Base
end
class Faker::NatoPhoneticAlphabet < Faker::Base
end
class Faker::Number < Faker::Base
end
class Faker::Omniauth < Faker::Base
end
class Faker::PhoneNumber < Faker::Base
end
class Faker::Placeholdit < Faker::Base
end
class Faker::ProgrammingLanguage < Faker::Base
end
class Faker::Relationship < Faker::Base
end
module Faker::Religion
end
class Faker::Restaurant < Faker::Base
end
class Faker::Science < Faker::Base
end
class Faker::SlackEmoji < Faker::Base
end
class Faker::Source < Faker::Base
end
class Faker::SouthAfrica < Faker::Base
end
class Faker::Space < Faker::Base
end
class Faker::String < Faker::Base
end
class Faker::Stripe < Faker::Base
end
class Faker::Subscription < Faker::Base
end
class Faker::Superhero < Faker::Base
end
class Faker::Tea < Faker::Base
end
class Faker::Team < Faker::Base
end
class Faker::Theater < Faker::Base
end
class Faker::Time < Faker::Base
end
class Faker::Twitter < Faker::Base
end
class Faker::Types < Faker::Base
end
class Faker::University < Faker::Base
end
class Faker::Vehicle < Faker::Base
end
class Faker::Verb < Faker::Base
end
class Faker::VulnerabilityIdentifier < Faker::Base
end
class Faker::WorldCup < Faker::Base
end
class Faker::Fantasy
end
class Faker::Fantasy::Tolkien < Faker::Base
end
class Faker::Games
end
class Faker::Games::ClashOfClans < Faker::Base
end
class Faker::Games::Control < Faker::Base
end
class Faker::Games::DnD < Faker::Base
end
class Faker::Games::Dota < Faker::Base
end
class Faker::Games::ElderScrolls < Faker::Base
end
class Faker::Games::Fallout < Faker::Base
end
class Faker::Games::FinalFantasyXIV < Faker::Base
end
class Faker::Game < Faker::Base
end
class Faker::Games::HalfLife < Faker::Base
end
class Faker::Games::Heroes < Faker::Base
end
class Faker::Games::HeroesOfTheStorm < Faker::Base
end
class Faker::Games::LeagueOfLegends < Faker::Base
end
class Faker::Games::Minecraft < Faker::Base
end
class Faker::Games::Myst < Faker::Base
end
class Faker::Games::Overwatch < Faker::Base
end
class Faker::Games::Pokemon < Faker::Base
end
class Faker::Games::SonicTheHedgehog < Faker::Base
end
class Faker::Games::StreetFighter < Faker::Base
end
class Faker::Games::SuperMario < Faker::Base
end
class Faker::Games::SuperSmashBros < Faker::Base
end
class Faker::Games::Tarkov < Faker::Base
end
class Faker::Games::Touhou < Faker::Base
end
class Faker::Games::WarhammerFantasy < Faker::Base
end
class Faker::Games::Witcher < Faker::Base
end
class Faker::Games::WorldOfWarcraft < Faker::Base
end
class Faker::Games::Zelda < Faker::Base
end
class Faker::JapaneseMedia
  include Faker::Deprecator
end
class Faker::JapaneseMedia::Conan < Faker::Base
end
class Faker::JapaneseMedia::CowboyBebop < Faker::Base
end
class Faker::JapaneseMedia::Doraemon < Faker::Base
end
class Faker::JapaneseMedia::DragonBall < Faker::Base
end
class Faker::JapaneseMedia::FullmetalAlchemistBrotherhood < Faker::Base
end
class Faker::JapaneseMedia::KamenRider < Faker::Base
end
class InvalidName___Class_0x00___UnavailableInEra_42 < StandardError
end
class Faker::JapaneseMedia::Naruto < Faker::Base
end
class Faker::JapaneseMedia::OnePiece < Faker::Base
end
class Faker::JapaneseMedia::StudioGhibli < Faker::Base
end
class Faker::JapaneseMedia::SwordArtOnline < Faker::Base
end
class Faker::Locations
end
class Faker::Locations::Australia < Faker::Base
end
class Faker::Movies
end
class Faker::Movies::Avatar < Faker::Base
end
class Faker::Movies::BackToTheFuture < Faker::Base
end
class Faker::Movies::Departed < Faker::Base
end
class Faker::Movies::Ghostbusters < Faker::Base
end
class Faker::Movies::Hackers < Faker::Base
end
class Faker::Movies::HarryPotter < Faker::Base
end
class Faker::Movies::HitchhikersGuideToTheGalaxy < Faker::Base
end
class Faker::Movies::Hobbit < Faker::Base
end
class Faker::Movies::HowToTrainYourDragon < Faker::Base
end
class Faker::Movies::Lebowski < Faker::Base
end
class Faker::Movies::LordOfTheRings < Faker::Base
end
class Faker::Movie < Faker::Base
end
class Faker::Movies::PrincessBride < Faker::Base
end
class Faker::Movies::StarWars < Faker::Base
end
class Faker::Movies::TheRoom < Faker::Base
end
class Faker::Movies::Tron < Faker::Base
end
class Faker::Movies::VForVendetta < Faker::Base
end
class Faker::Music < Faker::Base
end
class Faker::Music::GratefulDead < Faker::Base
end
class Faker::Music::Hiphop < Faker::Base
end
class Faker::Music::Opera < Faker::Base
end
class Faker::Music::PearlJam < Faker::Base
end
class Faker::Music::Phish < Faker::Base
end
class Faker::Music::Prince < Faker::Base
end
class Faker::Music::RockBand < Faker::Base
end
class Faker::Music::Rush < Faker::Base
end
class Faker::Music::SmashingPumpkins < Faker::Base
end
class Faker::Music::UmphreysMcgee < Faker::Base
end
class Faker::Quotes
end
class Faker::Quotes::Chiquito < Faker::Base
end
class Faker::Quote < Faker::Base
end
class Faker::Quotes::Rajnikanth < Faker::Base
end
class Faker::Quotes::Shakespeare < Faker::Base
end
class Faker::Religion::Bible < Faker::Base
end
class Faker::Sports
end
class Faker::Sports::Basketball < Faker::Base
end
class Faker::Sports::Chess < Faker::Base
end
class Faker::Sports::Football < Faker::Base
end
class Faker::Sports::Mountaineering < Faker::Base
end
class Faker::Sport < Faker::Base
end
class Faker::Sports::Volleyball < Faker::Base
end
class Faker::Travel
end
class Faker::Travel::Airport < Faker::Base
end
class Faker::Travel::TrainStation < Faker::Base
end
class Faker::TvShows
end
class Faker::TvShows::AquaTeenHungerForce < Faker::Base
end
class Faker::TvShows::Archer < Faker::Base
end
class Faker::TvShows::BigBangTheory < Faker::Base
end
class Faker::TvShows::BojackHorseman < Faker::Base
end
class Faker::TvShows::BreakingBad < Faker::Base
end
class Faker::TvShows::BrooklynNineNine < Faker::Base
end
class Faker::TvShows::Buffy < Faker::Base
end
class Faker::TvShows::Community < Faker::Base
end
class Faker::TvShows::DrWho < Faker::Base
end
class Faker::TvShows::DumbAndDumber < Faker::Base
end
class Faker::TvShows::FamilyGuy < Faker::Base
end
class Faker::TvShows::FinalSpace < Faker::Base
end
class Faker::TvShows::Friends < Faker::Base
end
class Faker::TvShows::Futurama < Faker::Base
end
class Faker::TvShows::GameOfThrones < Faker::Base
end
class Faker::TvShows::HeyArnold < Faker::Base
end
class Faker::TvShows::HowIMetYourMother < Faker::Base
end
class Faker::TvShows::MichaelScott < Faker::Base
end
class Faker::TvShows::NewGirl < Faker::Base
end
class Faker::TvShows::ParksAndRec < Faker::Base
end
class Faker::TvShows::RickAndMorty < Faker::Base
end
class Faker::TvShows::RuPaul < Faker::Base
end
class Faker::TvShows::Seinfeld < Faker::Base
end
class Faker::TvShows::SiliconValley < Faker::Base
end
class Faker::TvShows::Simpsons < Faker::Base
end
class Faker::TvShows::SouthPark < Faker::Base
end
class Faker::TvShows::Spongebob < Faker::Base
end
class Faker::TvShows::StarTrek < Faker::Base
end
class Faker::TvShows::Stargate < Faker::Base
end
class Faker::TvShows::StrangerThings < Faker::Base
end
class Faker::TvShows::Suits < Faker::Base
end
class Faker::TvShows::Supernatural < Faker::Base
end
class Faker::TvShows::TheExpanse < Faker::Base
end
class Faker::TvShows::TheFreshPrinceOfBelAir < Faker::Base
end
class Faker::TvShows::TheITCrowd < Faker::Base
end
class Faker::TvShows::TheOffice < Faker::Base
end
class Faker::TvShows::TheThickOfIt < Faker::Base
end
class Faker::TvShows::TwinPeaks < Faker::Base
end
class Faker::TvShows::VentureBros < Faker::Base
end
module Faker::Config
end
class Faker::Base
end
