# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-progressbar/all/ruby-progressbar.rbi
#
# ruby-progressbar-1.13.0

class ProgressBar
end
module ProgressBar::Components
end
class ProgressBar::Components::Bar
end
class ProgressBar::Components::Percentage
end
class ProgressBar::Components::Rate
end
class ProgressBar::Components::Time
end
class ProgressBar::Components::Title
end
module ProgressBar::Format
end
class ProgressBar::Format::Formatter
end
class ProgressBar::Format::Molecule
end
class ProgressBar::Format::String < String
end
module ProgressBar::Calculators
end
class ProgressBar::Calculators::Length
end
class ProgressBar::Throttle
end
class ProgressBar::Output
end
module ProgressBar::Outputs
end
class ProgressBar::Outputs::NonTty < ProgressBar::Output
end
class ProgressBar::Outputs::Tty < ProgressBar::Output
end
class ProgressBar::InvalidProgressError < RuntimeError
end
class ProgressBar::Progress
end
module ProgressBar::Projectors
end
class ProgressBar::Projectors::SmoothedAverage
end
class ProgressBar::Projector
end
class ProgressBar::Time
end
class ProgressBar::Timer
end
class ProgressBar::Base
  extend Forwardable
end
module ProgressBar::Refinements
end
module ProgressBar::Refinements::Enumerator
end
