# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/site_ruby/all/site_ruby.rbi
#
# site_ruby-3.2.0

module Bundler
end
class Bundler::SelfManager
  def autoswitching_applies?; end
  def current_version; end
  def find_latest_matching_spec(requirement); end
  def find_latest_matching_spec_from_collection(specs, requirement); end
  def install(spec); end
  def install_and_restart_with(version); end
  def install_locked_bundler_and_restart_with_it_if_needed; end
  def installed?; end
  def local_specs; end
  def lockfile_version; end
  def needs_switching?; end
  def released?(version); end
  def remote_specs; end
  def resolve_update_version_from(target); end
  def restart_version; end
  def restart_with(version); end
  def restart_with_locked_bundler_if_needed; end
  def ruby_can_restart_with_same_arguments?; end
  def running?(version); end
  def running_older_than?(version); end
  def update_bundler_and_restart_with_it_if_needed(target); end
  def updating?; end
end
module Kernel
  def self.gem(dep, *reqs); end
end
