# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/stringio/all/stringio.rbi
#
# stringio-3.1.1

class StringIO
  def pread(*arg0); end
  def self.new(*arg0); end
  def self.open(*arg0); end
end
